Patch 1
asheroto/winget-install pull request #23
Opened 2023-10-17 22:21 UTC by uffemcev

2023-10-19 17:44 UTC, asheroto reviewed
I think this looks good! Thanks again.

I believe only one change to make and then we can approve.

2023-10-19 17:44 UTC, asheroto commented on winget-install.ps1
> +        Write-Output "It may breaks your custom batch files and ps1 scripts with extra commands!"
This should say "It may break your custom..."

2023-10-19 17:45 UTC, asheroto requested changes
Changing status to `request changes`

2023-10-19 17:47 UTC, uffemcev commented on winget-install.ps1
> +        Write-Output "It may breaks your custom batch files and ps1 scripts with extra commands!"
Done! :)

2023-10-20 03:30 UTC, uffemcev commented
So, can you approve this now?

2023-10-20 21:57 UTC, asheroto commented
Looks great, thank you again. Sorry for the delay, I've been busy with my day job. 😊

2023-10-20 21:57 UTC, merged