added support for Windows Server < 2022
asheroto/winget-install pull request #43
Opened 2024-05-17 14:57 UTC by MatthiasGuelck

The changes have been tested with Windows Server 2019, but should also work with Windows Server 2016.

2024-05-20 23:29 UTC, asheroto commented
I haven't forgotten about this, just been busy. Will look at it soon.

2024-05-23 05:36 UTC, asheroto commented
This looks like a great idea. Does not appear to work on Server 2016.

![image](https://github.com/asheroto/winget-install/assets/49938263/184a0efb-b929-4add-ba85-74c333f0cd4d)

Server 2019 looks good at first, but `winget` doesn't actually work.

![image](https://github.com/asheroto/winget-install/assets/49938263/d1f244d3-accd-442d-bd2b-a288960ba75a)

2024-05-23 05:48 UTC, MatthiasGuelck commented
The result of Windows Server 2016 (Unspecific Error) is not very helpful.
Maybe I can find another PC with Windows Server 2016 to test it myself.

During my test on a Windows Server 2019, everything ran smoothly.
Can you repeat the call to winget from a CMD?

2024-05-23 05:57 UTC, asheroto commented
You can use Hyper-V and install the Server 2016 ISO even the trial one to test. If I get a chance tomorrow I'll try to grab better output of the error.

2024-05-23 06:01 UTC, MatthiasGuelck commented
Good suggestion.
But the problem with 2019 is very unusual.
winget seems to run.
What happens with "winget upgrade --all"?

2024-05-23 13:28 UTC, MatthiasGuelck commented
Further investigation:
Error "failed with error 0x80073CFD" indicates that the Windows version is too old.
Therefore, I have changed the script so that at least Windows Server 2019 is required.

2024-05-23 21:37 UTC, asheroto requested changes
It'll install, but I can't get it to work on Server 2019 as-is.

![image](https://github.com/asheroto/winget-install/assets/49938263/33c6afc0-0d3e-4134-a21c-012741f06756)

As you mentioned, after installing Visual C++ Redistributable, I was able to get the commands to work on Server 2019. Also was able to install programs.

![image](https://github.com/asheroto/winget-install/assets/49938263/85ef3a8b-539c-462c-b6f1-b4487193542b)

So now we just need to have the script check that if the OS is Server 2019, and it doesn't have Visual C++ Redistributable, install it.

2024-05-23 21:37 UTC, asheroto commented on winget-install.ps1
> +          $WinGetFolderPath = "$(Resolve-Path -Path "$env:ProgramFiles\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe")" # the outer '"' surrounding $(Resolve-Path...) are essential f
Let's try to use the combine method here rather than backslash. This is to help folks in other countries with a different directory separator.

This method works well:
https://stackoverflow.com/a/25893843/11404332

2024-05-23 21:39 UTC, asheroto commented
I think you can use the appropriate aka.ms link from here:
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

2024-05-24 14:15 UTC, MatthiasGuelck commented
I have taken your suggestions into account and tested the script successfully with the following systems after the last changes:
Windows LTSC (1809)
Windows Server 2019
Windows Server 2022

2024-05-30 18:38 UTC, asheroto commented
Sorry for the delay, I was out of town.

On Server 2019, `winget` still shows as an unrecognized command until you restart the computer. I will add in some help text to account for that.

Thanks for your work on this!

2024-05-30 18:38 UTC, merged

2024-05-31 05:37 UTC, asheroto commented
@MatthiasGuelck I've made some adjustments to the script that improve upon your additions. Pushing out version `4.1.0` now. I also gave you credit in the README.

Thanks again!

2024-06-03 07:03 UTC, MatthiasGuelck commented
> Sorry for the delay, I was out of town.
> 
> On Server 2019, `winget` still shows as an unrecognized command until you restart the computer. I will add in some help text to account for that.
> 
> Thanks for your work on this!

2024-06-03 07:58 UTC, MatthiasGuelck commented
> On Server 2019, `winget` still shows as an unrecognized command until you restart the computer. I will add in some help text to account for that.

@asheroto I can't confirm that at all.
I have now carried out the installation with my fork on several PCs with Server 2019 and winget was available immediately after running the script on all attempts.
This applies both to a fresh installation as Hyper-V and to PCs that have been in operation for some time.
Then I tested it again on a fresh Hyper-V installation with your latest script.
No reboot was necessary:
![image](https://github.com/asheroto/winget-install/assets/138014262/7c1fb8c4-6ecb-437b-8136-1badda06b8fa)

I also don't see why there should be a problem that is solved by a reboot.
The whole mess that is necessary with Server 2019 is only due to the fact that the "App Execution Aliases" are not created correctly in Server 2019.
They do appear here...
![image](https://github.com/asheroto/winget-install/assets/138014262/a1f1cd66-231f-42e1-8605-3a063d32fb33)


... but not here:
![image](https://github.com/asheroto/winget-install/assets/138014262/633ab77a-1c55-4413-8dbd-adbd17a094a3)

Unfortunately, I don't know how to repair the faulty "App Execution Alias".
Therefore, the access rights for the path to winget must be adjusted and the path must be added.
Both must take effect immediately without a reboot.

2024-06-03 08:08 UTC, asheroto commented
Agreed, upon retesting I no longer have that issue. No matter, I didn't end up adding in any extra instructions anyway. 😊

Thanks for your help!

2024-06-03 11:47 UTC, MatthiasGuelck commented
Some final comments:
 - Server 2019 should be added to your "About"
 - the section in the script titled "Visual C++ Redistributable (Server 2019 only)" includes not only VCRedist, but also the customization of access rights and paths.
This also applies to the next heading "# Download & install Visual C++ Redistributable if it's Server 2019"
- in all other sections the Write-Debug outputs end with "`n`n", but not in this section - intentional?

2024-06-04 05:07 UTC, MatthiasGuelck commented
No further comments from my side. 
I've seen [#44](https://github.com/asheroto/winget-install/issues/44), but doesn't that also apply to VCLibs and UI.Xaml?
There is also no check before download and installation whether they are already available.

2024-06-04 21:23 UTC, asheroto commented
True, I suppose I should check those too. Visual C++ is more commonly installed but either way won't hurt to check before installing the others.

2024-06-05 21:17 UTC, asheroto commented
Since VCLibs and UI.Xaml are part of the `Add-AppxProvisionedPackage` command, I think I might just leave it in there to avoid any unnecessary complication.

In testing with Windows Sandbox, I removed VCLibs as it was already installed, but then the installation failed when installing winget. So.... I guess it just really wants the dependency when installing.